sudo: required
services:
  - docker

before_install:
  - gem update --system
  - docker build -t anasrezk/react-ssr-starter -f Dockerfile.dev .

scripts:
  - docker run anasrezk/react-ssr-starter npm run test -- --coverage --passWithNoTests
